M48
; DRILL file {KiCad (6.0.4-0)} date Monday, March 28, 2022 at 11:15:47 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-28T23:15:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.4906Y-3.4469
X4.3843Y-3.4469
T2
X3.074Y-3.937
X4.8Y-3.937
T0
M30
